### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by Louis-He** [junhaoliao/ReCrossy-Road#1]
How are U guys doing?

**Comment by junhaoliao** [comment]
very good~ its basically done and we are fixing some minor bugs. how about u guys

**Comment by Louis-He** [comment]
Same. Maybe can get it fully work this weekend XD

**Comment by Louis-He** [comment]
Surprisingly, we already finished our project. XD

**Comment by junhaoliao** [comment]
We finished as well. surprise
